### ISSUE TITLE
Why is this using ReadStream from 'tty' instead of 'stream'?

### ISSUE THREAD

**Issue by tracker1** [Claviz/xlstream#1]
Just noticing that this is using ReadStream from 'tty', I realize it's only for type hinting, but wouldn't it work from the 'stream' module?

**Comment by jansivans** [comment]
I haven't found `ReadStream` in the `stream` module.
Did you mean `fs` module?

**Comment by jansivans** [comment]
Anyway it is used just for type checking, so not a big deal whcih module to use.

**Comment by tracker1** [comment]
@jansivans `import {Readable} from 'stream';`[1]

I know it's just for type checking, just threw me off a bit when seeing it.

[1] https://nodejs.org/api/stream.html#stream_class_stream_readable
