### ISSUE TITLE
A personal newbie question

### ISSUE THREAD

**Issue by 64J0** [Claviz/xlstream#16]
Hi, is it possible to create a readStream from a file that isn't stored in the system? Like, the file is only in the memory of the operating system pointed by a variable in the code.

**Comment by jansivans** [comment]
Hello.
It would be nice if you can provide some code snippet of what you are trying to accomplish or how "pointed by a variable" looks like because an answer may vary depending on this information.

**Comment by 64J0** [comment]
Alright, I'll try to illustrate the question. Actually in my code I'm making some changes in a XLSX file that is the files tree. To do this I'm using the <a href="https://github.com/exceljs/exceljs#readme">Excel JS package</a> . Everything goes well and this is the code:

```javascript
const path = require("path");
const ExcelJS = require("exceljs");
const mongoose = require("mongoose");

// Model to use Mongoose and get info from Database
const Projetos = mongoose.model("Projetos");

// This file exists in this location, it is like a layout to the 
// spreadsheets
const filePath = path.resolve(__dirname, "../assets/teste.xlsx");

exports.genExcelFile = async (id) => {
  const res = await Projetos.findById(id);

  const workBook = new ExcelJS.Workbook();

  const saida = await workBook.xlsx
    .readFile(filePath)
    .then(function (workBook) {
      workBook.lastModifiedBy = "ADM Full Engenharia";
      workBook.modified = new Date();

      // SOME TASKS TO CHANGE THE FILE

      return workBook;
    })
    .then((workBook) => {
      // This is only a test I've done before
      return workBook;
    })
    .catch((err) => console.log(err));

  return { saida, numGRD: res.numGRD };
};
```

Alright, this code is like a controller that I call in other function like this:

```javascript
const fs = require('fs');
const repository = require("../repositories/excel-repository");

exports.genExcelFile = async (req, res) => {
  try {
    await repository
      .genExcelFile(req.params.id)
      .then((PlanilhaEditada) => {
        const workBook = PlanilhaEditada.saida;
        const { numGRD } = PlanilhaEditada;

        // SET HEADERS

        const fileName = `GRD_${numGRD}.xlsx`;
        res.attachment(fileName);
        // Doesn't works because I need to save the file in 
        // some place
        // return fs.createWriteStream(workBook); 
        // But this works, like, it creates a stream with the 
        // response object of Express I think
        return workBook.xlsx.write(res); 
      })
      .catch((err) => {
        throw new Error(err);
      });
    return { ok: true };
  } catch (e) {
    // Some code here
  }
};
```

My question is in the end of the second code, in the line that says: return fs.createWriteStream(workBook);  // Doesn't works, because I need to have a path to the file.

Alright, and finishing I want to say that I'm really a newbie in the streams universe! Thanks.

**Comment by haakondr** [comment]
I think I have a similar use case. I would want to parse excel files uploaded to a express server. In this setup, the file is not present on my file system, but available in memory. 

I could of course write the file to a temp file system, but this introduces an additional I/O overhead that I would like to avoid.

I would like to suggest the possibility of passing in a file buffer as an alternative to "filePath". 

Something like this
```
const fileStream = fs.createReadStream('some-file.xlsx');
getXlsxStream({
  fileStream: fileStream,
});
```

In my case, I need support for the Readable interface https://nodejs.org/api/stream.html#stream_class_stream_readable. I am using multer in my express server and plan to use req.file.stream in my incoming requests.

I don't know if it would be best to support multiple types and do type checking internally or have explicit argument names (for instance, xlsx library accepts string, file, buffer as "data" argument in its read function).

**Comment by jansivans** [comment]
Main idea of this library is that you can open and load a file without reading all of it contents into memory using excessive amounts of RAM. So I think there is no point to use this library if your whole file is already inside memory. 
My suggestion is to check some other libraries that fit your requirements.
