### ISSUE TITLE
Incorrect Date Formatting

### ISSUE THREAD

**Issue by Chazza** [Claviz/xlstream#17]
Hi,

I'm reading through an excel sheet which has the following dates set:

> 
> - 02/06/2020
> - 05/06/2020

XLStream formats these as:

> 
> - 6/2/20
> - 05/06/2020

This ends up meaning invalid dates are returned which make it a mess, are there any ways round this?

Also, yes this is U.K. format (DD/MM/YYYY), the year gets snipped to 2 characters etc.

**Comment by jansivans** [comment]
Hi!
Can you provide a file with this issue? I couldn't reproduce it with mine.
Also have you looked at raw result? Date stored there is a number and can be formatted as you wish.
![image](https://user-images.githubusercontent.com/5667073/84260968-9fb70c00-ab23-11ea-854e-0cc5e4f7475d.png)

**Comment by Chazza** [comment]
Yeah, thank you.
