### ISSUE TITLE
Does it support csv format?

### ISSUE THREAD

**Issue by nrtkrishna** [Claviz/xlstream#22]

**Comment by jansivans** [comment]
Nope. 
But there are lot's of CSV streaming libraries available in NPM.
Are they missing some specific functionality you want?

**Comment by nrtkrishna** [comment]
I just started working on reading large files. My files usually have up to 1 million records and the format can be xls, xlsx and csv. I am exploring options. I found this one to be one of the best. Thanks for the quick reply.

**Comment by jansivans** [comment]
I think there won't be a problem if you combine different libraries in your solution.
If you'll encounter some problem with this library and/or with parsing XLSX files, feel free to open up another issue.
