### ISSUE TITLE
Use a read stream instead of a path?

### ISSUE THREAD

**Issue by santiq** [Claviz/xlstream#23]
Hi, 

I have a use case where my file is in a remote server, I'm downloading it (using a stream) and storing it in a temp file (using write stream), then using this library to read from it.

Would it be nice if I could stream my download directly into the xlstream. 
Any ideas?

(maybe similar to #16)

**Comment by jansivans** [comment]
Hello.
XLSX is a zip file and because of this it can't be streamed like you desribed. 
You need to download file first.

**Comment by santiq** [comment]
@jansivans 
Alright make sense, thanks!

**Comment by Eywek** [comment]
Hi,

I've found a library that works pretty well that allow streaming directly zip files (https://www.npmjs.com/package/unzip-stream), maybe it can be used in this package?
