### ISSUE TITLE
How can I stop sending new events?

### ISSUE THREAD

**Issue by davidutramn** [Claviz/xlstream#25]
HI,

I am doing some validations on the data, so if there is an error, I would like to stop sending more.
Currently, I am using `stream.pause`, and then `stream.destroy`, is this okay?

Here is a part of my code

```
const stream = await getXlsxStream({
    filePath: file.path,
    sheet: 0,
    ignoreEmpty: true
});

stream.on('data', async x => {
    ...
    if (true) {
        stream.pause();
    }
});
stream.on('pause', function () {
    stream.destroy();
})
stream.on('error', function () {
    reject('not ok');
})
stream.on('end', x => {
    resolve(data);
});
```

**Comment by jansivans** [comment]
Hi.
I would suggest you using an [async iteration](https://nodejs.org/api/stream.html#stream_streams_compatibility_with_async_generators_and_async_iterators) approach.
This way your code will be much cleaner and you won't have to deal with stream events.
Also you will know exactly when your stream is stopped.
I've created some example of how to use this approach below:
```js
const { getXlsxStream } = require('xlstream');

(async () => {
    const stream = await getXlsxStream({
        filePath: './data.xlsx',
        sheet: 0,
    });
    try {
        for await (const data of stream) {
            console.log(data);
            if (data.raw.obj.A === 100) {
                throw new Error('oops');
            }
            // Code below will just stop a stream.
            // if (data.raw.obj.A === 100) {
            //     break;
            // }
        }
    } catch (err) {
        console.log(err)
    }
})();
```
Let me know if I have understood and answered your question correctly.

**Comment by davidutramn** [comment]
@jansivans 
Thank you, it worked for me, and my code is much smaller now.
