### ISSUE TITLE
Large File Issues

### ISSUE THREAD

**Issue by arrrrny** [Claviz/xlstream#27]
I have a file 13 Mb 36K rows and 160 columns, I am getting below error, If I reduce the row count to 100 it works. Any idea what might be the issue?

C:\Users\serda\zuzu\data-loader\node_modules\xlstream\lib\index.js:266
                        stream.pipe(saxStream({
                               ^
TypeError: Cannot read property 'pipe' of undefined
    at C:\Users\serda\zuzu\data-loader\node_modules\xlstream\lib\index.js:266:32
    at C:\Users\serda\zuzu\data-loader\node_modules\node-stream-zip\node_stream_zip.js:377:24
    at StreamZip.openEntry (C:\Users\serda\zuzu\data-loader\node_modules\node-stream-zip\node_stream_zip.js:429:24)
    at StreamZip.stream (C:\Users\serda\zuzu\data-loader\node_modules\node-stream-zip\node_stream_zip.js:375:21)
    at processStyles (C:\Users\serda\zuzu\data-loader\node_modules\xlstream\lib\index.js:265:25)
    at EntryVerifyStream.<anonymous> (C:\Users\serda\zuzu\data-loader\node_modules\xlstream\lib\index.js:298:29)

**Comment by jansivans** [comment]
Hi.
Please provide a file and source code to reproduce your bug.

**Comment by arrrrny** [comment]
[InventoryExport_9-21-2020-15-24-42.xlsx](https://github.com/Claviz/xlstream/files/5261733/InventoryExport_9-21-2020-15-24-42.xlsx)

  const { getXlsxStream } = require('xlstream');
    (async () => {
      const stream = await getXlsxStream({
        filePath: filePath,
        sheet: "InventoryExport",
      });
      stream.on('data', x => console.log(x));
    })();

**Comment by jansivans** [comment]
I have a workaround for you - if you try and save this file using Excel everything will work perfectly.
It looks like contents of this file is having irregular XLSX structure. 
What program was used to create this file?

**Comment by jansivans** [comment]
Here is a link for re-saved file: https://drive.google.com/file/d/1oja6uENzidZdQgI3SQfTVXBxRm9wuiOL/view?usp=sharing

**Comment by arrrrny** [comment]
Hi, thanks for fast reply, but this will be a file client will upload, So I need to detect the issue. I believe it is the new line character at the last line. But how can I delete that record? When I re-save the file on Libre it works as well

**Comment by jansivans** [comment]
Of course that is just a workaround. I'll investigate and try to fix tommorrow.

**Comment by arrrrny** [comment]
Awesome, thanks!

**Comment by jansivans** [comment]
I have found three issues (described below) and fixed them. 
Please check new version **2.2.0** of `xlstream`.

#### `x` namespace
Basically XLSX contains of zipped XML files and under the hood `xlstream` unzips archive and parses the XML files.
To parse, for example, a row of data, it needs to find `<row></row>` tags.
Surprisingly your files had `<x:row></x:row>` tags instead.
After a reasearch I have figured out that `x` prefix is a XML namespace and XLSX files can sometimes have it (usually when it was generated by using OpenXML).

#### Incorrect mapping of sheets
Internally `xlstream` incorrectly mapped sheet IDs with actual sheet files inside XLSX zip.

#### Failing on missing `styles.xml` file
If the XLSX archive doesn't contain `styles.xml` file, `xlstream` would throw an exception.

**Comment by arrrrny** [comment]
Interesting, thank you so much. I will test now and let you know

**Comment by arrrrny** [comment]
works great! thank you!

**Comment by rajatjasuja23** [comment]
Hey @arrrrny @jansivans  
Can you please share how much time this file will take to convert xlsx to json?
I have around 50k rows with respect to 50 columns and the file size is 18mb,and i'm using npm xlsx library to convert 50k rows which is taking 60 secs of time which is too much

**Comment by jansivans** [comment]
Hi @rajatjasuja23.
If you can provide your file (or similar, if it contains private data), I'll test it for you.

**Comment by rajatjasuja23** [comment]
PFA
[50000_Test.xlsx](https://github.com/Claviz/xlstream/files/5879617/50000_Test.xlsx)

**Comment by jansivans** [comment]
```
Parsed 59025 rows
time elapsed: 1:21.351 (m:ss.mmm)
```
Keep in mind that `xlsx` library puts everything into RAM, but `xlstream` does it with minimal memory footprint.
