### ISSUE TITLE
Error handling for invalid xlsx files.

### ISSUE THREAD

**Issue by Tiim** [Claviz/xlstream#3]
I have an app that lets users upload data via an xlsx table. How do I make sure the xlsx file is valid?

The following snipped crashes node even though i wrap it in a try catch block when file is not a valid xlsx file.
```js
// TODO: crashes if file is not a valid xlsx file
export async function importExcelFile(file) {
  let stream;
  try {
    stream = await getXlsxStream({
      filePath: file,
      sheet: 0,
      withHeader: true,
      ignoreEmpty: true,
    });
  } catch (err) {
    console.log(err);
  }
  const array = [];
  stream.on('data', async (x) => {
    stream.pause();
    const res = await handle(x);
    array.push(res);
    stream.resume();
  });
  stream.on('error', (error) => {
    console.log(error);
  });
  await new Promise((resolve) => stream.on('end', () => resolve()));
  return array;
}
```

Stacktrace: 
```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Bad archive')
     at StreamZip.emit (events.js:185:17)
     at FsRead.readUntilFoundCallback [as callback] (/code/node_modules/node-stream-zip/node_stream_zip.js:200:25)
     at FsRead.readCallback (/code/node_modules/node-stream-zip/node_stream_zip.js:858:21)
     at FSReqCallback.wrapper [as oncomplete] (fs.js:466:5)
```

I do check if the file extension is *.xlsx but I don't want users crashing my server by just renaming a textfile from `text.txt` to `text.xlsx`.

**Comment by jansivans** [comment]
Hi.
Thanks for a report. I have released 1.0.11 version of this package with a potential fix.
You now will be able to catch error without crashing whole app.
Please let me know if issue is fixed for you.

**Comment by Tiim** [comment]
This works :+1: thanks!

**Comment by jeanjoe** [comment]
Hi @jansivans sorry to come back to this issue, I am getting `uncaughtException` error and the whole app crashing in `v2.5.3` even when wrapped in `try-catch`

How can I catch this error without crashing the whole app

**Comment by jansivans** [comment]
Hi @jeanjoe!
Please share a code snippet and `.xlsx` file to reproduce your issue.
