### ISSUE TITLE
Node v15 issue

### ISSUE THREAD

**Issue by arrrrny** [Claviz/xlstream#33]
Package saxophone@0.6.1 is giving issue 
npm WARN EBADENGINE   package: 'saxophone@0.6.1',
npm WARN EBADENGINE   required: { node: '8 || 10 || 12 || 13' },

**Comment by jansivans** [comment]
Hi!
I have removed `saxophone` from dependencies.
Please check `2.3.2` version of `xlstream` and let me know if issue is fixed for you.

**Comment by arrrrny** [comment]
awesome! thanks
