### ISSUE TITLE
Support for Excel created with MS Excel 2003 or 97 ?

### ISSUE THREAD

**Issue by santiq** [Claviz/xlstream#34]
Hi there

When I try to parse this file, which I suspect was created with Excel 2003 or 97, I got a "Bad Archive" error.

 I think it comes from within the `node-stream-zip`?

[file_with_cfb_extension_or_excel_2003.xls.zip](https://github.com/Claviz/xlstream/files/5830902/file_with_cfb_extension_or_excel_2003.xls.zip)

Content is trivial and without any format:
![Screen Shot 2021-01-18 at 11 44 45](https://user-images.githubusercontent.com/7070683/104929400-95df6c00-5982-11eb-8d2e-149bbfd9a9d5.png)

What can I do about it?

**Comment by jansivans** [comment]
Hi.
Unfortunately `XLS` is very different from `XLSX`.
`XLSX` is a zip archive of `XML` files.
Implementing library for parsing `XLS` would require absolutely different approach.
Sorry, I can't help you this time😀

**Comment by santiq** [comment]
No problem! Thanks for the quick response :)
