### ISSUE TITLE
Is possible to get the chunk size for progress bar usage

### ISSUE THREAD

**Issue by rognales** [Claviz/xlstream#38]
Hi, i'm trying to add progress bar as I stream read the files.
For that, i need the current chunk size loaded
Total size i can get from filestat.

Is it possible?

**Comment by jansivans** [comment]
Hi.
There is one problem with an XLSX file - actually it is a ZIP archive with some files under the hood.
So comparing current chunk size to full XLSX file size is wrong - it must be compared to currently processing sheet size.
And you can't get this size unless you unzip whole XLSX.

However, I have found a solution and starting from **xlstream 2.4.0** `data` event emits `totalSheetSize` and `processedSheetSize` which can be used for your progress bar:
```JSON
{ 
    "raw": { 
        "obj": { "A": "hello", "B": 123.123 }, 
        "arr": [ "hello", 123.123 ] 
    },
    "formatted": { 
        "obj": { "A": "hello", "B": 123 }, 
        "arr": [ "hello", 123 ] 
    },
    "header": [],
    "totalSheetSize": 1110,
    "processedSheetSize": 500
}
```

Please let me know if it works for you.

**Comment by AlexTimo** [comment]
Hi @rognales, do you have further comments? If not, we'd be closing this issue.

**Comment by rognales** [comment]
Sorry for the late reply. I got all it need to feed the progress bar. Thx guys for the prompt response!
