### ISSUE TITLE
Error: Can't resolve 'fs' in node_modules/node-stream-zip

### ISSUE THREAD

**Issue by nilamGlobant** [Claviz/xlstream#42]
Hi team,
I am trying to use this package in Angular 12, however getting issues:
To fix initial issues I made some changes in angular.json and tsconfig.json ;

Angular,json(inside build ):  "allowedCommonJsDependencies": [
              "path",
              "stream",
              "util",
              "zlib",
              "assert"
            ]

tsconfig.json
inside compilerOption: "paths": {
      "path": ["./node_modules/path-browserify"],
      "stream": ["./node_modules/stream-browserify"],
      "zlib": ["./node_modules/browserify-zlib"],
      "util": ["./node_modules/util"],
      "assert": ["./node_modules/assert"]
    }

after adding above code resolved other error but not able to resolve below error,

/node_modules/node-stream-zip/node_stream_zip.js:7:9-22 - Error: Module not found: Error: Can't resolve 'fs' in 'applicationPath/node_modules/node-stream-zip'

**Comment by jansivans** [comment]
Hello.
This is a node.js library.
It can't be used inside browser because it accesses user's file system.
