### ISSUE TITLE
Forwarding errors from `node-stream-zip`

### ISSUE THREAD

**Issue by danielchiu** [Claviz/xlstream#55]
Hello! We're using `xlstream` with great success - thank you :)

Occasionally, we hit errors from inside the library, specifically `Cannot read properties of undefined (reading 'pipe')`. Looking at the [source code](https://github.com/Claviz/xlstream/blob/af0c0c027c9d7195f92bba84d038e82277fa4fbf/src/index.ts#L367), it looks like the `stream` is undefined. 

This `stream` comes from `node-stream-zip`, and indeed in the the types it looks like the [stream is optional](https://github.com/antelle/node-stream-zip/blob/7c5d50393418b261668b0dd4c8d9ccaa9ac913ce/node_stream_zip.d.ts#L177), presumably when there is an error passed in.

We unfortunately don't have a repro, but will attempt to find one. Have you seen this happen before? I'm also curious whether it'd be possible to surface the error from `node-stream-zip` rather than hitting the exception on `.pipe()`.

**Comment by jansivans** [comment]
Hello!
You might be correct - if the `stream` parameter is optional, it appears that it will be `undefined` when the `err` is passed to the callback. However, `xlstream` doesn't seem to handle `err`, which is why you receive an inaccurate error message. 
I can attempt to fix this issue based on our assumptions (for instance, by rethrowing `err`), but this doesn't guarantee that the error will be resolved for your specific problem. 
Therefore, I would greatly appreciate it if you could provide or create an `.xlsx` file that I can use for reproduction purposes.

**Comment by danielchiu** [comment]
Hi - thank you! 

I would love to provide an `.xlsx` repro, but don't currently have one since they are user-provided files. We added additional tracking so we'll know better next time, and I'll let you know! Rethrowing the `node-stream-zip` error will likely also make the situation clearer.

**Comment by danielchiu** [comment]
Thanks for bumping! We forked the repo with error forwarding, and now at least have the base error:
```
Received error from node-stream-zip: Error: Invalid local header
    at ZipEntry.readDataHeader (/opt/render/project/src/node_modules/.pnpm/node-stream-zip@1.15.0/node_modules/node-stream-zip/node_stream_zip.js:850:19)
```

It's inconsistent in that the same file will not always manifest the issue, and the only online reference is https://github.com/tschaub/mock-fs/issues/349#issue-1137598152. Best guess is something concurrency-related. Have you seen this before in your usage of `node-stream-zip`?

**Comment by AlexTimo** [comment]
I don't think we do run into this one with any regularity. Would be really helpful if you could provide us a sample of your script and an Excel file that triggers this issue, even if sporadically.

**Comment by danielchiu** [comment]
Not the easiest to isolate but will give it a shot!

**Comment by danielchiu** [comment]
Apologies for the delay while I was traveling - feel free to do whatever you wish with https://github.com/Claviz/xlstream/pull/57!
