### ISSUE TITLE
Write large Excel file

### ISSUE THREAD

**Issue by dulkith** [Claviz/xlstream#8]
Is there way to add new columns and data to large excel file (~1GB)

**Comment by jansivans** [comment]
Hi.
This library is designed only to read data from Excel.
However, you can use https://github.com/Claviz/bellboy to write streamed data somewhere.
There is no "Excel" destination yet (you can write it by yourself and contribute), but CSV destination is planned - https://github.com/Claviz/bellboy/issues/6
